### ISSUE TITLE
Seems the JSON Data file is not found 

### ISSUE THREAD

**Issue by Yunheng-Tian** [morph-kgc/morph-kgc#283]
Hello,

I'm using the RML engine for a university project. Before I tried RML Mapper version 7.0.0 and it succeeded to map the JSON data to RDF KG. And now I tried to use the morph-kgc engine to map the data. 

Here is a simple JSON data: 
![image](https://github.com/user-attachments/assets/027e6ef2-ca25-4883-9a1b-c89778c193fc)

And the mapping file as below: 
![image](https://github.com/user-attachments/assets/bb299232-72e4-454c-bb48-10c0317071da)

I use morph-kgc as a library as below:
![image](https://github.com/user-attachments/assets/b2348673-ad9d-484b-9f29-2a58680a5679)

It seems the mapping file works good, but no triples were generated. I'm wondering if it's the problem that the JSON file is not found. 
![image](https://github.com/user-attachments/assets/ca977784-b029-4b89-98c8-11d82e4885cf)

Environment :
OS: Windows 10
Python version: 3.10
Morph-KGC version: 2.8

Could you help me to have a look at it? Thank you!

**Comment by lovrozagar** [comment]
Hi @Yunheng-Tian ,

It looks like you might be encountering an issue where the JSON data is not being properly mapped to RDF triples, likely due to a misconfiguration with the file path or JSONPath expressions.

Here are a few steps to troubleshoot:

Check the File Path: Ensure that the JSON file path is correct and that the file is accessible by the script. If the file is not found, Morph-KGC will not generate any triples.

Validate the Mapping File: Make sure your mapping file has the correct logical source and JSONPath iterator. Here's an example template:

@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .

<#Mapping> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source "data.json" ;  # Ensure correct path
    rml:referenceFormulation ql:JSONPath ; 
    rml:iterator "$.items[*]" ;  # Ensure JSONPath is correct
  ] ;
  rr:subjectMap [
    rr:template "http://example.com/{id}" ;
  ] ;
  rr:predicateObjectMap [
    rr:predicate <http://example.com/name> ;
    rr:objectMap [ rml:reference "$.name" ] ;
  ] .
Use a Better JSONPath Library: If the JSONPath you are using is complex and the current library is not handling it well, consider switching to a more robust JSONPath library (e.g., jsonpath-ng), as the Morph-KGC team has discussed moving towards better support for JSONPath​

Enable Logging: Use debugging or logging features to track down any issues related to file access or mapping failures. Sometimes enabling detailed logs can give you a clue about what went wrong.

Try these steps to see if it resolves the issue, and if not, share more details about the specific error messages you're seeing for further assistance!

**Comment by Yunheng-Tian** [comment]
Hello,

Thank you for quick reply. I tried what you mentioned above, but it still did not work.  I did not get any error information. And I just tried again with RML Mapper, it seems that the JSON file and the Mapping file are good. 

Below is another attempt with morph-kgc, seems that it should be working, but just no results
![image](https://github.com/user-attachments/assets/14a1d4f8-5107-46fb-9fae-4e81ad3ef657)

**Comment by lovrozagar** [comment]
Hello @Yunheng-Tian ,

Thanks for the update! I can see you're still encountering issues with Morph-KGC, especially with the error messages in your logs. Let's address these directly:

Check the Error Details: From the error logs you shared, it looks like there might be an issue with the configuration or how the JSON file is being accessed. Make sure that the file paths are correct and that the JSON structure matches what your mapping expects.

Validation Steps:

JSON Structure: Ensure that the JSON file has a proper structure. You can validate it using online tools to confirm there are no syntax errors.
Mapping Reference: Double-check your mapping file, especially the references to the JSON paths. Sometimes small typos can lead to the mapping not being recognized.
Simplifying Mapping: As a troubleshooting step, try to simplify your mapping file to a basic version that only focuses on a few key elements. This can help isolate whether the issue is with the mapping complexity.

Enable Verbose Logging: If you haven’t already, enabling verbose logging can provide deeper insights into what's going wrong during the execution. Look for any warnings or errors that could point you to the root cause.

Consider Alternative Libraries: If the current JSONPath library isn't working as expected, consider switching to a different one, like jsonpath-ng, which has been mentioned in the community for its robustness.

If after trying these suggestions you’re still stuck, please share any new error messages or logs. That information will be vital in diagnosing the issue more effectively.

Let me know how this goes.

**Comment by arenas-guerrero-julian** [comment]
Hi @Yunheng-Tian,

Most probably the problem comes from the JSONPath expression in the mapping. The JSONPath syntax used by morph-kgc can be consulted [here](https://github.com/sean2077/jsonpath-python?tab=readme-ov-file#jsonpath-syntax).

As commented by @lovrozagar , the library currently used for the evaluation of JSONPath ([jsonpath-python](https://github.com/sean2077/jsonpath-python)) is limited and we may need to change the library for better support of JSONPath (see #269).

Could you share the mapping and example data as text (instead of as an image) so that I can reproduce the problem?

**Comment by Yunheng-Tian** [comment]
Hi @arenas-guerrero-julian,

Thank you for your response.

The JSON example is as follows:
```JSON
[
    {
        "id": "HotelRoom:room_101",
        "type": "HotelRoom",
        "hasLocation": {
            "type": "Text",
            "value": "Floor:1",
            "metadata": {}
        },
        "name": {
            "type": "Text",
            "value": "room_101",
            "metadata": {}
        }
    }
]
```

And the mapping file is as follows:
```python
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix ex: <http://example.com#> .
@prefix brick: <https://brickschema.org/schema/1.1/Brick#> .
@prefix rec: <https://w3id.org/rec/core#> .

ex:MappingHotelRoom
    a rr:TriplesMap ;
    rml:logicalSource [
        rml:source "preprocessed_entities_5rooms.json" ;
        rml:referenceFormulation ql:JSONPath ;
        rml:iterator "$[?(@.type == 'HotelRoom')]" ;
    ] ;
    rr:subjectMap [
        rr:template "http://example.com/hotel/{id}" ;
        rr:class rec:Room ;
    ] ;
    rr:predicateObjectMap [
        rr:predicate brick:hasLocation ;
        rr:objectMap [
            rml:reference "hasLocation.value" ;
        ] ;
    ] ;
    rr:predicateObjectMap [
        rr:predicate rdfs:label ;
        rr:objectMap [
            rml:reference "name.value" ;
        ] ;
    ] .
```

**Comment by arenas-guerrero-julian** [comment]
Thanks @djs0109 . The workaround you suggest make unit test to fail (#291), so I decided not to include it. However, your finding can be taken into account by users when writing JSONPath expressions so that they work in morph-kgc.

I close this issue as this will be eventually solved by migrating the JSONPath library #269.
